### ISSUE TITLE
It is unable to download the voice in wave file.

### ISSUE THREAD

**Issue by jenish2154** [jonelo/jAdapterForNativeTTS#6]

**Comment by jonelo** [comment]
more details from your private message:

> I have gone through your JAdaptiveNativeTTS deeply, but here i 
am facing an issue regarding downloading microsoft Zira voice 
in wav fie instead of speaking it?

thank you for your question @jenish2154. Saving to a wav file instead of speaking it is not supported.
Not a bug, it works as designed.
